export const KEY = {
  PERSISTENCE_KEY: "NAVIGATION_STATE",
  PREFERENCES_KEY: "APP_PREFERENCES",
  ACCESS_TOKEN: "id_token",
  REFRESH_TOKEN: "refresh_token",
  INPUT_CHANGE: "INPUT_CHANGE",
  INPUT_BLUR: "INPUT_BLUR",
  FORMAT_DATETIME_MSSQL: "YYYY-MM-DD HH:mm:ss",
};
