const ACTION_TYPES = {
  API_PENDING: "API_PENDING",
  API_SUCCESS: "API_SUCCESS",
  API_ERROR: "API_ERROR",
  SET_BUDGETS: "SET_BUDGETS",
  DELETE_BUDGETS: "DELETE_BUDGETS",
  SET_ERROR: "SET_ERROR",
  SET_LOADING: "SET_LOADING",
};
export default ACTION_TYPES;
