const ACTION_TYPES = {
  API_PENDING: "API_PENDING",
  API_SUCCESS: "API_SUCCESS",
  API_ERROR: "API_ERROR",
  SET_BUDGETS: "SET_BUDGETS",
  DELETE_BUDGETS: "DELETE_BUDGETS",
  SET_ERROR: "SET_ERROR",
  SET_LOADING: "SET_LOADING",
  SET_LOGIN: "LOGIN",
  SET_LOGOUT: "LOGOUT",
  SET_BUDGETID: "SET_BUDGETID",
  SET_BUDGETMONTH: "SET_BUDGETMONTH",
  SET_GRAPHDATAAMOUNT: "SET_GRAPHDATAAMOUNT",
  SET_GRAPHDATAWEEK: "SET_GRAPHDATAWEEK",
};
export default ACTION_TYPES;
